### ISSUE TITLE
Geofence notify Worker issue

### ISSUE THREAD

**Issue by poshakjaiswal** [Hussienfahmy/Location-Reminder-App#1]
E  Could not instantiate com.udacity.project4.locationreminders.geofence.GeofenceNotifyWorker
                                                                                                    java.lang.NoSuchMethodException: com.udacity.project4.locationreminders.geofence.GeofenceNotifyWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
                                                                                                    	at java.lang.Class.getConstructor0(Class.java:2332)
                                                                                                    	at java.lang.Class.getDeclaredConstructor(Class.java:2170)
                                                                                                    	at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
                                                                                                    	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
                                                                                                    	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
                                                                                                    	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)

**Comment by Hussienfahmy** [comment]
Could you please explain wat are you trying to do, provide the piece of code throwed this error.
